In [1]:
from pycaret.classification import *
import pandas as pd

In [3]:
data = pd.read_csv("Student_performance_data _.csv")

In [5]:
data.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0

In [7]:
clf = setup(data, target='GradeClass' , session_id=123, 
            numeric_features=['Age','StudyTimeWeekly','Absences'],
            categorical_features=['Gender','Ethnicity','ParentalEducation','Tutoring','ParentalSupport',
                                  'Extracurricular','Sports','Music','Volunteering'],
            ignore_features=['StudentID','GPA'])

In [9]:
best_model = compare_models()

In [10]:
save_model(best_model , "student_performance_model")

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Age', 'StudyTimeWeekly',
                                              'Absences'],
                                     transformer=SimpleImputer(add_indicator=False,
                                                               copy=True,
                                                               fill_value=None,
                                                               keep_empty_features=False,
                                                               missing_values=nan,
                                                               strategy='mean'))),
                 ('categorical_imputer',
                  TransformerWrapper(exclude=None,
                                     include=['Gender...
                                                               handle_missing='return_nan',
                                                               handle_unknown='value',
                                                               return_df=True,
                                                               use_cat_names=True,
                                                               verbose=0))),
                 ('trained_model',
                  LogisticRegression(C=1.0, class_weight=None, dual=False,
                                     fit_intercept=True, intercept_scaling=1,
                                     l1_ratio=None, max_iter=1000,
                                     multi_class='auto', n_jobs=None,
                                     penalty='l2', random_state=123,
                                     solver='lbfgs', tol=0.0001, verbose=0,
                                     warm_start=False))],
          verbose=False),
 'student_performance_model.pkl')

In [11]:
create_api(best_model , 'student_performance_api')

API successfully created. This function only creates a POST API, it doesn't run it automatically. To run your API, please run this command --> !python student_performance_api.py